### PR TITLE
Update azuredeploy.json

### PR DESCRIPTION
**Pull request by JeremyLikness**
Fix server farm id

### CODE REVIEW

**Comment by JeremyLikness** [comment]
Ready to merge. Tested deployment with change.

**Comment by olgamarti** [comment]
Hi @JeremyLikness  I merged the PR #93 with the same change. Can you check if your issue is solved? Thanks!

**Comment by JeremyLikness** [comment]
Looks good to me!

**Comment by olgamarti** [comment]
Fixed on PR #93

**Pull request closed without merging**
